image: registry.forge.hefr.ch/embsys/arm-none-eabi-builder:latest

stages:
  - check
  - build
  - upload
  - deploy

check:
  stage: check
  script:
    - find src -name '*.[ch]' | xargs cpplint --filter=-,+whitespace/tab,+whitespace/line_length,+readability/utf8 --output=vs7

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cpack --config CPackConfig.cmake
    - cpack --config CPackSourceConfig.cmake
  artifacts:
    paths:
      - build/libbbb-*-arm-none-eabi.tar.gz
      - build/libbbb-*-Source.tar.gz
    expire_in: never

upload:
  stage: upload
  script:
    - artifact=$(echo build/libbbb-*-arm-none-eabi.tar.gz)
    - artifact_base=$(basename $artifact)
    - artifact_version=$(echo $artifact_base | sed 's/^[^-]*-\([^-]*\)-.*/\1/')
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${artifact} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/libbbb/${artifact_version}/${artifact_base}"'

update_docker_image:
  stage: deploy
  script:
    - curl -X POST -F token=${GITLAB_CI_TOKEN} -F ref=master https://gitlab.forge.hefr.ch/api/v4/projects/5385/trigger/pipeline
