image: heiafr/arm-none-eabi-builder:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=arm-none-eabi.cmake ..
    - make
    - cpack --config CPackConfig.cmake
    - cpack --config CPackSourceConfig.cmake
  artifacts:
    paths:
      - build/libbbb-*-arm-none-eabi.tar.gz
      - build/libbbb-*-Source.tar.gz

update_docker_image:
  stage: deploy
  script:
    - curl -s -X POST ${docker_hub_trigger_url} >/dev/null
