image: registry.forge.hefr.ch/embsys/arm-none-eabi-builder:latest

stages:
  - check
  - build
  - deploy

check:
  stage: check
  script:
    - find src -name '*.[ch]' | xargs cpplint --filter=-,+whitespace/tab,+whitespace/line_length,+readability/utf8 --output=vs7

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=arm-none-eabi.cmake ..
    - make
    - cpack --config CPackConfig.cmake
    - cpack --config CPackSourceConfig.cmake
  artifacts:
    paths:
      - build/libbbb-*-arm-none-eabi.tar.gz
      - build/libbbb-*-Source.tar.gz

update_docker_image:
  stage: deploy
  script:
    - curl -X POST -F token=${GITLAB_CI_TOKEN} -F ref=master https://gitlab.forge.hefr.ch/api/v4/projects/5385/trigger/pipeline
